# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NS-Challeng-iOS' do
  inhibit_all_warnings!
  use_frameworks!
  pod 'Moya'
  pod 'Kingfisher'

  target 'NS-Challeng-iOSTests' do
    inherit! :search_paths
    pod 'Quick', '= 2.2.0'
    pod 'Nimble', '= 8.0.4'
  end
end
