# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Gists' do
  inhibit_all_warnings!
  use_frameworks!
  pod 'Moya'
  pod 'Kingfisher'

  target 'GistsTests' do
    inherit! :search_paths
    pod 'Quick', '= 2.2.0'
    pod 'Nimble', '= 8.0.4'
  end
end
